config/routes.rb
Rails.application.routes.draw do

  root 'books#index'

  resources :books do 
    resources  :chapters
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :chapters, dependent: :destroy
  validates :title, presence: true
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :book

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :fetch_book, only: [:show, :destroy, :edit, :update, :preview]

  def index
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update_attributes(book_params)
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @book.destroy
    redirect_to root_path, notice: "Book deleted successfully"
  end

private
  def book_params
    params.require(:book).permit(:title, :caption)
  end

  def fetch_book
    @book = Book.find(params[:id])
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :fetch_book
  before_action :fetch_chapter, only: [:show, :edit, :update, :destroy]

  def new
    @chapter = @book.chapters.new
  end

  def create
    @chapter = @book.chapters.new(chapter_params)
    if @chapter.save
      redirect_to book_chapter_path(@book,@chapter)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @chapter.update_attributes(chapter_params)
      redirect_to book_chapter_path(@book,@chapter)
    else
      render :edit
    end
  end

  def destroy
    @chapter.destroy
    redirect_to book_path(@book), notice: "Chapter was successfully deleted"
  end

private

  def fetch_chapter
    @chapter = @book.chapters.find(params[:id])
  end

  def fetch_book
    @book = Book.find(params[:book_id])
  end

  def chapter_params
    params.require(:chapter).permit(:title, :notes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
  <%= f.input :title, placeholder: "Eg. how to play guitar" %>
  <%= f.input :caption %>
  <%= f.submit class: "btn btn-primary btn-lg" %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit <%= @book.title %></h1>
<%= render 'books/form' %>

app/views/books/index.html.erb
<%= link_to "Add a new Book", new_book_path, class: "pull-right btn btn-primary" %>
<h1>Pick a book to contribute</h1>
<% Book.all.each do |book| %>
  <div class="well">
    <h3><%= link_to book.title, book_path(book) %></h3>
    <p>
      <%= book.caption %>
    </p>
  </div>
<% end %>

app/views/books/new.html.erb
<h1>Add new Book</h1>
<%= render 'books/form' %>

app/views/books/show.html.erb
<%= link_to "Delete", book_path(@book), method: :delete, class: "btn btn-danger pull-right", data: {confirm: "Are you sure you want to delete the book?"} %>
<%= link_to "Edit", edit_book_path(@book), class: "btn btn-primary pull-right" %>
<%= link_to "Add Chapter", new_book_chapter_path(@book), class: "btn btn-primary pull-right" %>

<h1><%= @book.title %></h1>
<p><%= @book.caption %></p>
<table class="table table-striped table-hover">
  <% @book.chapters.each do |chapter| %>
  <tr>
    <td>
      <%= link_to chapter.title, book_chapter_path(@book,chapter) %>
    </td>
  </tr>
  <% end %>
</table>

app/views/chapters/_form.html.erb
<%= simple_form_for [@book,@chapter]   do |f| %>
  <%= f.input :title %>
  <%= f.input :notes %>
  <%= f.submit class: "btn btn-primary btn-lg" %>
<% end %>

app/views/chapters/edit.html.erb
<%= render 'chapters/form' %>

app/views/chapters/new.html.erb
<h1>Add Chapter to <%= link_to @book.title, book_path(@book) %></h1>
<%= render 'chapters/form' %>

app/views/chapters/show.html.erb
<%= link_to "Delete", book_chapter_path(@book,@chapter), method: :delete, class: "btn btn-danger pull-right", data: {confirm: "Are you sure you want to delete the chapter?"} %>
<%= link_to "Edit", edit_book_chapter_path(@book,@chapter), class: "btn btn-primary pull-right" %>
<h1><%= @chapter.title %>
  <small>from <%= link_to @book.title, book_path(@book) %></small>
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookAuthoringPortal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Author", root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Link</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:error] %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= flash[:error] %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>